2024-08-23 12:16:20,467 - INFO - Start code execution ...
2024-08-23 12:16:20,467 - ERROR - Uncaught exception
Traceback (most recent call last):
  File "C:\Users\Michael\Documents\GitHub\ssicsync\main.py", line 27, in <module>
    modelResults.runTrainingSummaryModel(logger)
  File "C:\Users\Michael\Documents\GitHub\ssicsync\controller.py", line 98, in runTrainingSummaryModel
    trainingSummaryModel(self, logger)
  File "C:\Users\Michael\Documents\GitHub\ssicsync\models\summaryModel\trainingSummaryModel.py", line 33, in trainingSummaryModel
    df_input = pd.read_excel("dataSources/ScrapedOutputFiles/pdfScrapedOutputs.csv")
  File "C:\Users\Michael\AppData\Roaming\Python\Python310\site-packages\pandas\io\excel\_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\Michael\AppData\Roaming\Python\Python310\site-packages\pandas\io\excel\_base.py", line 1500, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.
